/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainJavaSwing;

import javax.swing.*;

/**
 *
 * @author ASUS
 */

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    final int WIDTH = 625, HEIGHT = 534;
    //final int MENU_WIDTH = 200, MENU_HEIGHT = 50;
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        setSize(WIDTH, HEIGHT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        MenuJPane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Menu_JTabbedPane = new javax.swing.JTabbedPane();
        Search = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listResultSearch_JList = new javax.swing.JList<>();
        chooseLanguageSearch_JComboBox = new javax.swing.JComboBox<>();
        languageSearch_JLabel = new javax.swing.JLabel();
        searchInput_JTextField = new javax.swing.JTextField();
        findSearch_JButton = new javax.swing.JButton();
        History = new javax.swing.JPanel();
        languageHistory_JLabel = new javax.swing.JLabel();
        chooseLanguageHistory_JComboBox = new javax.swing.JComboBox<>();
        clearHistory_JButton = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        listResultHistory_JList = new javax.swing.JList<>();
        DefiJPanel = new javax.swing.JPanel();
        Defi_JTabbedPane = new javax.swing.JTabbedPane();
        Definition_JPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Revise_JPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        Add_JPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        Delete_JPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainFrame");

        MenuJPane.setBackground(new java.awt.Color(0, 0, 204));
        MenuJPane.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MenuJPane.setForeground(new java.awt.Color(255, 255, 255));
        MenuJPane.setAlignmentX(0.0F);
        MenuJPane.setAlignmentY(0.0F);
        MenuJPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                MenuJPaneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Dictionary");

        Menu_JTabbedPane.setToolTipText("");
        Menu_JTabbedPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Menu_JTabbedPaneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Search.setBackground(new java.awt.Color(204, 204, 204));

        listResultSearch_JList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        listResultSearch_JList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "result 1", "result 2", "result 3", "result 4", "result 5", "..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listResultSearch_JList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listResultSearch_JList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                listResultSearch_JListAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        listResultSearch_JList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listResultSearch_JListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listResultSearch_JList);

        chooseLanguageSearch_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGLISH", "VIETNAMESE" }));

        languageSearch_JLabel.setText(" LANGUAGE:");
        languageSearch_JLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        languageSearch_JLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                languageSearch_JLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        searchInput_JTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        searchInput_JTextField.setText("Search");
        searchInput_JTextField.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 5));
        searchInput_JTextField.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                searchInput_JTextFieldAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        searchInput_JTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchInput_JTextFieldMouseClicked(evt);
            }
        });
        searchInput_JTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInput_JTextFieldActionPerformed(evt);
            }
        });

        findSearch_JButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainJavaSwing/Image/search.png"))); // NOI18N
        findSearch_JButton.setText("Find");

        javax.swing.GroupLayout SearchLayout = new javax.swing.GroupLayout(Search);
        Search.setLayout(SearchLayout);
        SearchLayout.setHorizontalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(searchInput_JTextField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(SearchLayout.createSequentialGroup()
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SearchLayout.createSequentialGroup()
                        .addComponent(languageSearch_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseLanguageSearch_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(findSearch_JButton)))
                .addContainerGap())
        );
        SearchLayout.setVerticalGroup(
            SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SearchLayout.createSequentialGroup()
                .addGroup(SearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseLanguageSearch_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageSearch_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(searchInput_JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(findSearch_JButton))
        );

        Menu_JTabbedPane.addTab("SEARCH", Search);

        History.setBackground(new java.awt.Color(204, 204, 204));

        languageHistory_JLabel.setText(" LANGUAGE:");
        languageHistory_JLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 1));
        languageHistory_JLabel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                languageHistory_JLabelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        chooseLanguageHistory_JComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENGLISH", "VIETNAMESE" }));

        clearHistory_JButton.setText("CLEAR");
        clearHistory_JButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearHistory_JButtonActionPerformed(evt);
            }
        });

        listResultHistory_JList.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        listResultHistory_JList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "history 1", "history 2", "history 3", "history 4", "history 5", "..." };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listResultHistory_JList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane7.setViewportView(listResultHistory_JList);

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HistoryLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(clearHistory_JButton))
                    .addGroup(HistoryLayout.createSequentialGroup()
                        .addComponent(languageHistory_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chooseLanguageHistory_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jScrollPane7)
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseLanguageHistory_JComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(languageHistory_JLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearHistory_JButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu_JTabbedPane.addTab("HISTORY", History);

        javax.swing.GroupLayout MenuJPaneLayout = new javax.swing.GroupLayout(MenuJPane);
        MenuJPane.setLayout(MenuJPaneLayout);
        MenuJPaneLayout.setHorizontalGroup(
            MenuJPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuJPaneLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Menu_JTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        MenuJPaneLayout.setVerticalGroup(
            MenuJPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuJPaneLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu_JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        DefiJPanel.setBackground(new java.awt.Color(51, 51, 255));
        DefiJPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        DefiJPanel.setForeground(new java.awt.Color(255, 255, 255));
        DefiJPanel.setAlignmentX(0.0F);
        DefiJPanel.setAlignmentY(0.0F);
        DefiJPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                DefiJPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Defi_JTabbedPane.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Defi_JTabbedPaneAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        Definition_JPanel.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane3.setViewportView(jTextArea1);

        javax.swing.GroupLayout Definition_JPanelLayout = new javax.swing.GroupLayout(Definition_JPanel);
        Definition_JPanel.setLayout(Definition_JPanelLayout);
        Definition_JPanelLayout.setHorizontalGroup(
            Definition_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        Definition_JPanelLayout.setVerticalGroup(
            Definition_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Definition_JPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 35, Short.MAX_VALUE))
        );

        Defi_JTabbedPane.addTab("DEFINITION", Definition_JPanel);

        Revise_JPanel.setBackground(new java.awt.Color(204, 204, 204));
        Revise_JPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Revise_JPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        javax.swing.GroupLayout Revise_JPanelLayout = new javax.swing.GroupLayout(Revise_JPanel);
        Revise_JPanel.setLayout(Revise_JPanelLayout);
        Revise_JPanelLayout.setHorizontalGroup(
            Revise_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        Revise_JPanelLayout.setVerticalGroup(
            Revise_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        Defi_JTabbedPane.addTab("REVISE", Revise_JPanel);

        Add_JPanel.setBackground(new java.awt.Color(204, 204, 204));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane5.setViewportView(jTextArea3);

        javax.swing.GroupLayout Add_JPanelLayout = new javax.swing.GroupLayout(Add_JPanel);
        Add_JPanel.setLayout(Add_JPanelLayout);
        Add_JPanelLayout.setHorizontalGroup(
            Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        Add_JPanelLayout.setVerticalGroup(
            Add_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        Defi_JTabbedPane.addTab("ADD", Add_JPanel);

        Delete_JPanel.setBackground(new java.awt.Color(204, 204, 204));
        Delete_JPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Delete_JPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane6.setViewportView(jTextArea4);

        javax.swing.GroupLayout Delete_JPanelLayout = new javax.swing.GroupLayout(Delete_JPanel);
        Delete_JPanel.setLayout(Delete_JPanelLayout);
        Delete_JPanelLayout.setHorizontalGroup(
            Delete_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
        );
        Delete_JPanelLayout.setVerticalGroup(
            Delete_JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE)
        );

        Defi_JTabbedPane.addTab("DELETE", Delete_JPanel);

        javax.swing.GroupLayout DefiJPanelLayout = new javax.swing.GroupLayout(DefiJPanel);
        DefiJPanel.setLayout(DefiJPanelLayout);
        DefiJPanelLayout.setHorizontalGroup(
            DefiJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Defi_JTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        DefiJPanelLayout.setVerticalGroup(
            DefiJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DefiJPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Defi_JTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuJPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DefiJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuJPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DefiJPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuJPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_MenuJPaneAncestorAdded
        // TODO add your handling code here:  
    }//GEN-LAST:event_MenuJPaneAncestorAdded

    private void Menu_JTabbedPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Menu_JTabbedPaneAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu_JTabbedPaneAncestorAdded

    private void searchInput_JTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInput_JTextFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchInput_JTextFieldActionPerformed

    private void searchInput_JTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchInput_JTextFieldMouseClicked
        // TODO add your handling code here:
        searchInput_JTextField.setText("");
    }//GEN-LAST:event_searchInput_JTextFieldMouseClicked

    private void DefiJPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_DefiJPanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_DefiJPanelAncestorAdded

    private void Delete_JPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Delete_JPanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Delete_JPanelAncestorAdded

    private void Revise_JPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Revise_JPanelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Revise_JPanelAncestorAdded

    private void Defi_JTabbedPaneAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Defi_JTabbedPaneAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Defi_JTabbedPaneAncestorAdded

    private void languageSearch_JLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_languageSearch_JLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_languageSearch_JLabelAncestorAdded

    private void languageHistory_JLabelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_languageHistory_JLabelAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_languageHistory_JLabelAncestorAdded

    private void searchInput_JTextFieldAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_searchInput_JTextFieldAncestorAdded
        // TODO add your handling code here:
        searchInput_JTextField.setText("Search");
    }//GEN-LAST:event_searchInput_JTextFieldAncestorAdded

    private void listResultSearch_JListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listResultSearch_JListMouseClicked
        // TODO add your handling code here:
         if (listResultSearch_JList.getSelectedIndex() !=  -1) {
            String resultSearch = listResultSearch_JList.getSelectedValue();
            searchInput_JTextField.setText(resultSearch);
        }
    }//GEN-LAST:event_listResultSearch_JListMouseClicked

    
    private void listResultSearch_JListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_listResultSearch_JListAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_listResultSearch_JListAncestorAdded

    private void clearHistory_JButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearHistory_JButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearHistory_JButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Add_JPanel;
    private javax.swing.JPanel DefiJPanel;
    private javax.swing.JTabbedPane Defi_JTabbedPane;
    private javax.swing.JPanel Definition_JPanel;
    private javax.swing.JPanel Delete_JPanel;
    private javax.swing.JPanel History;
    private javax.swing.JPanel MenuJPane;
    private javax.swing.JTabbedPane Menu_JTabbedPane;
    private javax.swing.JPanel Revise_JPanel;
    private javax.swing.JPanel Search;
    private javax.swing.JComboBox<String> chooseLanguageHistory_JComboBox;
    private javax.swing.JComboBox<String> chooseLanguageSearch_JComboBox;
    private javax.swing.JButton clearHistory_JButton;
    private javax.swing.JButton findSearch_JButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel languageHistory_JLabel;
    private javax.swing.JLabel languageSearch_JLabel;
    private javax.swing.JList<String> listResultHistory_JList;
    private javax.swing.JList<String> listResultSearch_JList;
    private javax.swing.JTextField searchInput_JTextField;
    // End of variables declaration//GEN-END:variables
}
